### ISSUE TITLE
ADD projectriff/java-function@0.4.2

### ISSUE THREAD

**Issue by elbandito** [elbandito/buildpack-registry#1]
### Data

```toml
id = "projectriff/java-function"
version = "0.4.2"
addr = "gcr.io/projectriff/java-function@sha256:aeab8d5b5cfa4d06fa0a099a1ebf26ad953c146d79a845f9283dac3986e8cf1e"
```
